#!/bin/bash
# kcat Helper Commands for Kafka Management
# Usage: Run these commands from your terminal

BROKER="kafka:29092"

echo "=== kcat Helper Commands ==="
echo ""
echo "1. List cluster metadata (brokers, topics, partitions):"
echo "   docker exec biopro-kcat kcat -b $BROKER -L"
echo ""
echo "2. List all topics:"
echo "   docker exec biopro-kcat kcat -b $BROKER -L | grep 'topic'"
echo ""
echo "3. Consume messages from a topic (from beginning):"
echo "   docker exec biopro-kcat kcat -b $BROKER -C -t <topic-name> -o beginning"
echo ""
echo "4. Consume messages from a topic (last 10):"
echo "   docker exec biopro-kcat kcat -b $BROKER -C -t <topic-name> -o -10"
echo ""
echo "5. Consume messages with key and metadata:"
echo "   docker exec biopro-kcat kcat -b $BROKER -C -t <topic-name> -f 'Key: %k\nValue: %s\nPartition: %p\nOffset: %o\n---\n'"
echo ""
echo "6. Produce a message to a topic:"
echo "   echo 'your message' | docker exec -i biopro-kcat kcat -b $BROKER -P -t <topic-name>"
echo ""
echo "7. Produce a message with key:"
echo "   echo 'key:value' | docker exec -i biopro-kcat kcat -b $BROKER -P -t <topic-name> -K:"
echo ""
echo "8. Get topic configuration:"
echo "   docker exec biopro-kcat kcat -b $BROKER -L -t <topic-name>"
echo ""
echo "9. Monitor consumer group lag:"
echo "   docker exec biopro-kcat kcat -b $BROKER -L | grep -A 20 'consumer groups'"
echo ""
echo "10. Query watermarks (offset range) for a topic:"
echo "    docker exec biopro-kcat kcat -b $BROKER -Q -t <topic-name>"
echo ""
